export enum TransportStatut {
  EN_ATTENTE = 'EN_ATTENTE',
  ACCEPTEE = 'ACCEPTEE',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVEE = 'ARRIVEE',
  EN_COURS = 'EN_COURS',
  TERMINEE = 'TERMINEE',
  ANNULEE = 'ANNULEE',
}
